DROP TABLE IF EXISTS cash4life_numbers CASCADE;
DROP TABLE IF EXISTS megamillions_numbers CASCADE;
DROP TABLE IF EXISTS powerball_numbers CASCADE;
DROP TABLE IF EXISTS quickdraw_numbers CASCADE;
DROP TABLE IF EXISTS pick6_numbers CASCADE;
DROP TABLE IF EXISTS jerseycash5_numbers CASCADE;
DROP TABLE IF EXISTS pick4_numbers CASCADE;
DROP TABLE IF EXISTS pick3_numbers CASCADE;
